name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Get Conan Cache Key
        id: get-conan-cache-key
        run: |
          echo "cache-key=${{ runner.os }}-conan-${{ hashFiles('**/conanfile.txt', '**/conanfile.py') }}" >> $GITHUB_OUTPUT

      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan/data
            ~/.conan/downloads
          key: ${{ steps.get-conan-cache-key.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-conan-

      - name: Build Project
        run: |
          conan profile detect --force
          conan install . --build=missing --settings=build_type=RelWithDebInfo
          cmake --preset conan-relwithdebinfo
          cmake --build --target all --preset conan-relwithdebinfo

      - name: Run Google Tests
        run: build/RelWithDebInfo/StepEngine/test/test
