name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh

      - uses: extractions/setup-just@v2
        with:
          just-version: 1.5.0 # optional semver specification, otherwise latest

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Test
        run: just test
