name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          generator: Ninja
          cxx-compiler: clang++
          options: |
            CMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Run Google Tests
        run: ./build/relwithdebinfo/test/test
